// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhYksVSoYFsYkipD6pOb7NtAYEclY_-pI',
    appId: '1:778034441384:web:0beb7bb777c08b4f7d669d',
    messagingSenderId: '778034441384',
    projectId: 'to-do-f70ff',
    authDomain: 'to-do-f70ff.firebaseapp.com',
    storageBucket: 'to-do-f70ff.firebasestorage.app',
    measurementId: 'G-F1R1VMFEMV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0qEoTHBpg6u67wb9sX_t0iOaTbMjxgjA',
    appId: '1:778034441384:android:e856f26cfe20469d7d669d',
    messagingSenderId: '778034441384',
    projectId: 'to-do-f70ff',
    storageBucket: 'to-do-f70ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCW___CiTWt5aZHmjqLdP25L0CR1cuk2Y',
    appId: '1:778034441384:ios:ece2ee476ea778cc7d669d',
    messagingSenderId: '778034441384',
    projectId: 'to-do-f70ff',
    storageBucket: 'to-do-f70ff.firebasestorage.app',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCW___CiTWt5aZHmjqLdP25L0CR1cuk2Y',
    appId: '1:778034441384:ios:ece2ee476ea778cc7d669d',
    messagingSenderId: '778034441384',
    projectId: 'to-do-f70ff',
    storageBucket: 'to-do-f70ff.firebasestorage.app',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhYksVSoYFsYkipD6pOb7NtAYEclY_-pI',
    appId: '1:778034441384:web:a23305c7062a00ab7d669d',
    messagingSenderId: '778034441384',
    projectId: 'to-do-f70ff',
    authDomain: 'to-do-f70ff.firebaseapp.com',
    storageBucket: 'to-do-f70ff.firebasestorage.app',
    measurementId: 'G-ESYLKEF6F2',
  );
}
